name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "ea442e37-0cca-49d9-b187-82b76d78cafa"
          heroku_app_name: "raca-monitor" #Must be unique in Heroku
          heroku_email: "tinyswish@gmail.com"
          procfile: "web: node raca-monitor.js"
